# Generated by Django 3.2.5 on 2021-07-17 06:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210717_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name="Article's title")),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of created')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='usrimg',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='usrimg',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='whichcomment',
        ),
        migrations.RemoveField(
            model_name='document',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
